<html>
<head>
    <style type="text/css">
    table {
        border-collapse: collapse;
    }
    td {
        border: 1px solid black;
    }
    </style>
</head>
<body>
<h1>My Layout</h1>
<table>
<tr id="nakedphp_services">
<td>Services:</td>
<td><?php echo $this->layout()->nakedphp_services; ?></td>
</tr>
<tr id="nakedphp_session">
<td>Session bar:</td>
<td><?php echo $this->layout()->nakedphp_session; ?></td>
</tr>
<tr id="nakedphp_methods">
<td>Methods:</td>
<td><?php echo $this->layout()->nakedphp_methods; ?></td>
</tr>
<!--
<tr>
<td>History:</td>
<td><?php echo $this->layout()->nakedphp_history; ?></td>
</tr>
-->
</table>
<?php
echo $this->layout()->content;
?>
</body>
</html>
