<html>
<head>
    <?php 
    echo $this->headTitle()->setSeparator(' - ');
    echo $this->headStyle();
    ?>
    <style type="text/css">
    /* layout */
    body {
        margin: 0px;
        padding: 0px;
    }
    div#container {
    }
    div#header{
        height: 150px;
        border-bottom: 1px solid black;
    }
    div#methods {
        float: left;
        width: 25%;
        height: 300px;
    }
    div#object {
        margin-left: 25%;
        width: 66%;
    }

    /* header */
    #header table {
        width: 90%;
    }
    #header tr#nakedphp_services {
    }
    #header tr#nakedphp_session {
        height: 40px;
    }
    #header td.label {
        width: 25%;
    }
    #header td.content {
        width: 75%;
    }
    
    /* lists 
    div#header ul {
        list-style-type: none;
        padding: 0px;
        margin: 0px;
    }
    div#header li {
        float: left;
        padding-top: 4px;
        padding-bottom: 4px;
        padding-right: 10px;
        margin: 0px;
    }*/

    /* forms */
    form {
        background: white;
        width: 460px;
        margin: 5px auto;
        padding: 0px;
        overflow: auto;
    }

    form dt {
        padding: 0px;
        clear: both;
        width: 30%;
        float: left;
        text-align: right;
        margin: 5px 5px 5px 0px;
    }

    form dd {
        padding: 0px;
        float: left;
        width: 68%;
        margin: 5px 2px 5px 0px;
    }

    form input, form textarea, form select {
        margin: 0px 0px 2px 0px;
        padding: 0px;
    }

    form input[type="submit"] {
    }

    /*
    .required:before{content:'* '}

    .optional:before{content:'+ '}
    */

    /* tables */
    table {
        border-collapse: collapse;
    }
    td {
        border: 1px solid black;
    }

    /* hooks */
    #header dt.icon {
        float: left;
    }
    #header dt.icon a {
        display: block;
        height: 32px;
        line-height: 32px;
    }
    #header dd.button {
        float: left;
        padding: 0px;
        margin: 0px;
    }

    .icon {
        height: 32px;
    }

    .button.edit {
        height: 32px;
        padding: 0px;
    }
    .button.edit a {
        display: block;
        height: 32px;
        padding-left: 34px;
        margin-left: 0px;
        line-height: 32px;
        background: url(/graphic/buttons/edit.png) no-repeat left 0%;
    }
    .button.edit a:link, .button.edit a:visited {
        width: 0px;
        overflow: hidden;
    }
    .button.edit a:hover, .button.edit a:active {
        width: auto;
    }

    </style>
</head>
<body>
<div id="container">
    <div id="header">
        <table>
        <tr id="nakedphp_services">
        <td class="label">Services:</td>
        <td class="content"><?php echo $this->layout()->nakedphp_services; ?></td>
        </tr>
        <tr id="nakedphp_session">
        <td class="label">Session bar:</td>
        <td class="content"><?php echo $this->layout()->nakedphp_session; ?></td>
        </tr>
        <tr id="nakedphp_context">
        <td>Context:</td>
        <td><?php echo $this->layout()->nakedphp_context; ?></td>
        </tr>
        <!--
        <tr>
        <td>History:</td>
        <td><?php echo $this->layout()->nakedphp_history; ?></td>
        </tr>
        -->
        </table>
    </div>
    <div id="methods">
        <td><?php echo $this->layout()->nakedphp_methods; ?></td>
    </div>
    <div id="object">
    <?php
    echo $this->layout()->content;
    ?>
    </div>
</div>
</body>
</html>
